### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by KindDragon** [JanchEwgen/MQTT-SberGate#1]
Добавьте пожалуйста лицензию в проект

**Comment by JanchEwgen** [comment]
С удовольствием сделал бы это, если бы что-то в этом понимал.
По ходу для меня это будет сделать сложнее, чем самого агента.
Её можно где-нибудь скачать? ;)

**Comment by KindDragon** [comment]
Вот сайт есть https://choosealicense.com
Обычно либо MIT или GPL. Просто копируешь лицензию Copy license text to clipboard и вставляешь в файл LICENSE.txt. Github вроде подсказку тоже такую показывает https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#applying-a-license-to-a-repository-with-an-existing-license

Вот например у похожего проекта https://github.com/munrexio/yandex2mqtt/blob/master/LICENSE

**Comment by JanchEwgen** [comment]
Я всё-таки это сделал. Добавил какую-то лицензию. Правда не совсем понимаю что мне делать с Eclipse Paho™ MQTT Python Client который я использую и тупо включил в проект...
