### ISSUE TITLE
Сущность action не как relay

### ISSUE THREAD

**Issue by perfect-deform** [JanchEwgen/MQTT-SberGate#10]
Здравствуйте, подскажите пожалуйста, можно ли передавать сущность action не как relay, а именно как switch?
Хотелось бы из HA пробросить action от Xiaomi Wireless Switch Key WXKG01LM в Салют, чтобы управлять лампочками сбера. Relay, к сожалению, автоматизациями управлять не может.

**Comment by JanchEwgen** [comment]
Хотел ответить, что не получится, но засомневался. В текущей версии точно нет, а так надо пробовать. Если мы имеем переключатель заведенный в HA, то вроде как мы её можем пробросить в Салют, а в Салюте наверное можно настроить сценарий на этот выключатель, чтобы он был связан с лампочкой. Интересный поворот, даже не думал о таком. У меня есть лампочка от Сбера, но вот нет ни одного переключателя чтобы экспериментировать.
Не видел простых способов запихнуть устройства Салюта в HA, но такой вариант даёт некую надежду. Интересно попробовать, но очень сложно выбрать время. Если и будет что делаться, то наверное очень не скоро...

**Comment by perfect-deform** [comment]
Спасибо большое за ответ. Рад узнать что такое в целом возможно. Буду ждать обновлений

**Comment by JanchEwgen** [comment]
> Буду ждать обновлений

Можно пробовать обновляться. 1.0.12 добавлена трансляция input_boolean в scenario_button.
Не уверен что это то, что требовалось, так как нет слова action, но если создать переключатель в HA и настроить сценарий, то лампочка сбера включается и выключается и, на удивление, это быстро происходит.
