### ISSUE TITLE
Keep getting authentification errors

### ISSUE THREAD

**Issue by Opontios** [JanchEwgen/MQTT-SberGate#11]
Постоянные ошибки аутентификации, но функциональность аддона про этом не теряется.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:192
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:32:01 (1 occurrences)
Last logged: 11:32:01

[140705126939584] Received invalid command: {'type': 'auth', 'access_token': 'мой_токен'}
```

В чем может быть проблема?

**Comment by JanchEwgen** [comment]
Сложно сказать. А как часто такие записи появляются?
У себя я только одну запись четыре дня назад обнаружил. Никогда раньше не обращал на это внимание. Ещё бы лог от дополнения посмотреть, но, похоже, там сейчас это не найти, нужно пересмотреть работу с журналированием...

**Comment by Opontios** [comment]
Ну я заметил при каждой перезагрузке HA. В логе в режиме info ничего не видно, может переключить на какой-то другой режим?

**Comment by Opontios** [comment]
И еще вопрос. Вы настоятельно рекомендуете создать отдельного пользователя для работы с аддоном. Я не делал этого. Чем это может быть чревато?

**Comment by JanchEwgen** [comment]
> при каждой перезагрузке HA.

Посмотрел. Похоже я перемудрил с подключением. В следующей версии уберу.

**Comment by JanchEwgen** [comment]
> настоятельно рекомендуете создать отдельного пользователя

Типа по безопасности так более правильно. Чем может быть чревато? Особо ничем, просто права возможно ограничить и при анализе видно кто светом моргал...

**Comment by Opontios** [comment]
> В следующей версии уберу.

Благодарю!
