### ISSUE TITLE
Как обновить количество устройств в Салюте после изменений устройств в дополнении?

### ISSUE THREAD

**Issue by Bagunda** [JanchEwgen/MQTT-SberGate#12]
Первоначальную настройку сделал. Всё работает.
Потом добавил ещё устройство.
А в Салюте не вижу изменений.
Какова процедура обновления устройств в приложении Салюта?
Написать бы это в инструкции...

**Comment by JanchEwgen** [comment]
> Какова процедура обновления устройств в приложении Салюта?

Всё очень просто. Ставим галочки в веб-интерфейсе, изменения сразу летят в облако Сбер. Чтобы эти изменения увидеть в приложении Салют, возможно нужно обновить в нём состояние (свайп вниз в приложении).

**Comment by JanchEwgen** [comment]
> Написать бы это в инструкции...

Хотелось бы, но не получается.

**Comment by Bagunda** [comment]
> свайп вниз в приложении

Не появляются новые устройства при свайпе в низ на главной странице приложения "Салют"

**Comment by JanchEwgen** [comment]
Можно попробовать перезагрузить дополнение и проверить включены ли устройства в веб-интерфейсе. Попробовать выключить и включить и обновить в приложении Салют информацию. Должно работать. Других вариантов просто нет.
