### ISSUE TITLE
Прокидывание влажности для датчиков температуры

### ISSUE THREAD

**Issue by TohaRG2** [JanchEwgen/MQTT-SberGate#13]
Есть три разных датчика температуры, но в Салют от них приходят только показания температуры. Добавь пожалуйста еще и показания влажности воздуха.

**Comment by JanchEwgen** [comment]
Пока добавить не могу, так как у меня в HA нет подходящего устройства для экспериментов. У меня есть только датчики температуры. Поэтому пока не представляю как это выглядит. Со временем, может появится.

**Comment by TohaRG2** [comment]
Ну если вы в Москве, могу поделится. :) У меня не один

**Comment by JanchEwgen** [comment]
Не Москва. Можно виртуальный какой датчик замутить. У меня с народного мониторинга например температура и давление заведена. Немного не то. И непонятно как два датчика температуры и влажности из HA прокинуть в один общий датчик салют. А может бывает и у HA совмещённый. Но не посмотрев кишки, не поймёшь...
