### ISSUE TITLE
Комнаты в Салюте

### ISSUE THREAD

**Issue by TohaRG2** [JanchEwgen/MQTT-SberGate#14]
Заметил такую особенность, если в HA завести виртуальный переключатель input_boolean, то его комната (пространство) прокидывается в Салют, для остальных устройств нет. Хотя комната задана у всех устройств.
![image](https://github.com/JanchEwgen/MQTT-SberGate/assets/47621988/f284f98b-a229-4367-bf28-1aeb3ec75e28)

**Comment by JanchEwgen** [comment]
Странно. Должно работать. По крайней мере у меня на скриптах и переключателях работает. Местами в HA не совсем явно задаётся расположение, иногда оно наследуется от устройства и тогда HA не передаёт эту информацию каждой сущности. Вот с этим не знаю как быть. Да и не вижу смысла. Всё равно я пока так и не научился пробрасывать эти комнаты в салют. То, что на указанном скрине - это внутренняя база шлюза, которая обновляется по мере работы из разных мест.
И да, чтобы изменения появились нужно перезагрузить дополнение. 
![HA_SG](https://github.com/JanchEwgen/MQTT-SberGate/assets/46722670/6fc0bd7d-0db9-420d-9e3f-85aafb0a1942)

**Comment by JanchEwgen** [comment]
Возможно я что-то делаю не так. Но пока Салют упорно не принимает отправляемые расположения. Хотя в базе они и отображаются.

**Comment by TohaRG2** [comment]
Да, для скриптов тоже работает (просто у меня не были указаны). А вот для других устройств почему-то нет. Например,  зигби реле, подключенное в НА (пространство указано)
![image](https://github.com/JanchEwgen/MQTT-SberGate/assets/47621988/b10c87c7-1454-4942-96c0-df26769ca654)

но в плагине его не видно, и в Салют оно естественно не пробросилось. 
![image](https://github.com/JanchEwgen/MQTT-SberGate/assets/47621988/9eb6f595-f706-478d-9f6a-b2efb33e871e)

Для устройств у которых в плагине указана комната у меня она успешно пробрасывается, и скрипты/переключатели сразу отображаются в Салюте в нужной комнате (не надо их руками перетаскивать)

**Comment by JanchEwgen** [comment]
Прикольно. А у меня не пробрасываются устройства в нужные комнаты... ;)

**Comment by JanchEwgen** [comment]
HA вот в таком варианте не передаёт комнату туда, откуда я беру инфу
![Снимок1](https://github.com/JanchEwgen/MQTT-SberGate/assets/46722670/eeefb4aa-152f-4f3e-b665-12eba4dc38eb)
А если вот так сделать, то передаёт. Но судя по скрину с подсветкой кухни, там вроде таких настроек нет, хотя тоже через MQTT
![Снимок2](https://github.com/JanchEwgen/MQTT-SberGate/assets/46722670/e2829960-20d7-4660-bece-6d64b88e8ee9)

**Comment by TohaRG2** [comment]
Обновил сервер HA, не стал восстанавливать все из бэкапа (только отдельные элементы), соответственно снова пробовал много разного. Действительно, комната должна быть задана для "Объекта", а не для "Устройства". Т.е. если установить плагин и до настройки всей интеграции с Салютом прописать у Объектов, как вы выше указали пространство, отвязав его наследование от устройства, то при первом пробросе устройства в Салют, с комнатами все ок (работает и если очистить базу). Все устройства сразу раскидались по нужным комнатам (к сожалению не сделал скрин с телефона, где изначально вычитались комнаты из HA и Салют предложил указать как они будут сматчены в него).  Если же менять комнату после того, как устройство добавлено в Салют, то уже ничего не меняется. 
Еще раз спасибо за плагин. Надеюсь, придумаете что-нибудь с пробросом команд в Салют, вариант с пробросом input_boolean в scenario_button не самый удачный, хотя можно и его оставить, но и еще что-то пробрасывать как действия сценарной кнопки.
