### ISSUE TITLE
я так понял не может найти модели на сервере сбера?

### ISSUE THREAD

**Issue by dmitrialeksey** [JanchEwgen/MQTT-SberGate#2]
20230724-132838: switch: switch.2_do_not_disturb Лампа 2 do_not_disturb
20230724-132838: Неиспользуемый тип: sensor.knopka_action
20230724-132838: Неиспользуемый тип: sensor.knopka_battery
20230724-132838: Неиспользуемый тип: automation.knopka_lampa_1
20230724-132838: Неиспользуемый тип: automation.knopka_lampa_2
20230724-132838: Неиспользуемый тип: automation.knopka_vse_lampy
20230724-132839: SberDevice http_api_endpoint: https://mqtt-partners.iot.sberdevices.ru
20230724-132839: Файл моделей отсутствует. Получаем...
    return complexjson.loads(self.text, **kwargs)
20230724-132839: Connect OK SberDevices Broker, rc: 0
20230724-132839: SD Subscribed: 2 (0,)
20230724-132839: SD Subscribed: 3 (0,)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/sber-gate.py", line 408, in <module>
    SD_Models = requests.get(Options['sber-http_api_endpoint']+'/v1/mqtt-gate/models', headers=hds,auth=(Options['sber-mqtt_login'], Options['sber-mqtt_password'])).json()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by JanchEwgen** [comment]
Скорее всего. Сейчас модели не используются. Ранее использовались, пока не научился обходится без них. Надо будет как-нибудь этот кусок выпилить...

**Comment by dmitrialeksey** [comment]
Что-то они там у себя поменяли и все заработало.

**Comment by JanchEwgen** [comment]
> Что-то они там у себя поменяли

Недавно ещё похожую проблему словили. Решилось переустановкой аддона. Скорее всего какой-то неизвестный косяк при установке. Хотя если само собой заработало, тоже странно.

**Comment by MiroYar** [comment]
У меня похожая проблема:
`20240821-212453.293383: SberDevice http_api_endpoint: mqtts://mqtt-partners.iot.sberdevices.ru
20240821-212453.293558: Файл моделей отсутствует. Получаем...
    SD_Models = requests.get(Options['sber-http_api_endpoint']+'/v1/mqtt-gate/models', headers=hds,auth=(Options['sber-mqtt_login'], Options['sber-mqtt_password']))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'mqtts://mqtt-partners.iot.sberdevices.ru/v1/mqtt-gate/models'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped`
