### ISSUE TITLE
Нужна помощь!

### ISSUE THREAD

**Issue by mrQmpan** [JanchEwgen/MQTT-SberGate#3]
Все настроил, но в sber не появляется ни одно устройство, можно ли с вами связать для помощи?

**Comment by JanchEwgen** [comment]
Возможно нужно в настройках дополнения перейти в веб-интерфейс и выбрать нужные устройства.
Как-нибудь добавлю это в информацию...

**Comment by mrQmpan** [comment]
Да, мой друг, спасибо. устал уже перебирать что мог не так сделать) теперь всё получилось)

**Comment by DIMMonchik** [comment]
А как добавить репозиторий в дополнения? У меня сообщает https://github.com/JanchEwgen/MQTT-SberGate is not a valid add-on repository

**Comment by JanchEwgen** [comment]
Честно говоря не знаю о чём речь. Когда делал, хотел добавить в HAСS, но пришёл к выводу, что туда только интеграцию можно добавить, а аддон нет. Может с тех пор что-то изменилось. С репозиторием аддонов не разбирался, просто делал по какому-то образцу. Со временем может почитаю что-то в этом направлении, допилю если разбирусь. Но быстро врядли получится...

**Comment by DIMMonchik** [comment]
> Честно говоря не знаю о чём речь. Когда делал, хотел добавить в HAСS, но пришёл к выводу, что туда только интеграцию можно добавить, а аддон нет. Может с тех пор что-то изменилось. С репозиторием аддонов не разбирался, просто делал по какому-то образцу. Со временем может почитаю что-то в этом направлении, допилю если разбирусь. Но быстро врядли получится...

А есть инструкция как его ставить?

**Comment by mrQmpan** [comment]
> А как добавить репозиторий в дополнения? У меня сообщает https://github.com/JanchEwgen/MQTT-SberGate is not a valid add-on repository

Вы можете в ручную расположить этот аддон в папке addons в home assistant

У меня такой путь: /usr/share/hassio/addons/local/mqtt-sber-gate

**Comment by DIMMonchik** [comment]
> > А как добавить репозиторий в дополнения? У меня сообщает https://github.com/JanchEwgen/MQTT-SberGate is not a valid add-on repository
> 
> Вы можете в ручную расположить этот аддон в папке addons в home assistant
> 
> У меня такой путь: /usr/share/hassio/addons/local/mqtt-sber-gate

Спасибо. До этого сам догадался. Жаль что сенсоры и осветительные приборы не поддерживаются

**Comment by mrQmpan** [comment]
Я думаю добавить Сбер в ближайшее время их поддержку, а вообще у меня 5 колонок, и для управления умным домом, мне очень редко нужна инфа сенсоров от колонок

**Comment by AlekseyPetrov75** [comment]
У сбера появился агент для установки на сервер умного дома SberDevices IoT Agent. Но на HASS, в частности который идет образом на Raspberry Pi, не ставиться, как я понимаю из-за #урезанности линукса. Но вариант вроде как интересный. Риторический вопрос, его как то можно переделать для установки на HASS?

**Comment by JanchEwgen** [comment]
> У сбера появился агент для установки на сервер умного дома SberDevices IoT Agent.

Весьма интересное заявление. Ссылка есть на него? Очень хотелось бы посмотреть.
"Для установки на сервер умного дома" это очень расплывчатое и широкое понятие. В описании к [MQTT-SberGate](https://github.com/JanchEwgen/MQTT-SberGate) написано: "Правда список поддерживаемых контроллеров ограничивается всего лишь двумя: LogicMachine и Wiren Board." Уж не это ли имеется в виду?

**Comment by AlekseyPetrov75** [comment]
Да, установка вроде только как для Wiren Board, просто описание привлекло тем, как описана работа модуля. MQTT смотрит в обе стороны и тем самым чисто теоретически должна работать на любой системе. Вопрос в том, возможно ли на HASS поставить как-то и попробовать. Ваш аддон я все таки запустил, хотя и не с первого раза. Простота добавления сущности switch и script в Sber поразила. То что есть работает хорошо. Но вот обратной связи от HASS точно не хватает. Когда переключаешь выключатель в HASS он не передает данные в Sber.

**Comment by JanchEwgen** [comment]
> Да, установка вроде только как для Wiren Board, просто описание привлекло тем, как описана работа модуля. MQTT смотрит в обе стороны и тем самым чисто теоретически должна работать на любой системе.

Нууууу....  Именно этот агент и пошёл под реверс-инжиниринг  для создание того, что сейчас и есть. Я даже включил их Web-морду с настройками, так сказать на посмотреть. Уже даже не помню что там работает, а что нет.
В начале у меня тоже было два MQTT в обе стороны и это бы решило проблему обратной связи HASS с облаком Сбер, но это очень сильно усложняло настройку. В HASS тогда тоже нужно все устройства в MQTT преобразовывать или городить костыли. Поэтому я остановился на REST API от HA, а в таком варианте, чтобы отображать изменения в HA его нужно постоянно сканировать, что совсем не хорошо. Возможно я чего-то не знаю, может есть какой Web-Hook в HA, но пока до этого руки не дошли, хроническая нехватка времени... :( 
В принципе это всё я коротенечко в описании и написал (там, где "немного истории").

**Comment by JanchEwgen** [comment]
Кстати, сейчас зашёл по ссылке про REST API, а там оказывается рядом WebSocket API
Возможно это как раз то, что нужно, чтобы держать обе стороны под контролем. Вопрос только когда?
Возможно долгими, зимними вечерами... ;)
