### ISSUE TITLE
Версия 1.0.4 не запускается

### ISSUE THREAD

**Issue by AlekseyPetrov75** [JanchEwgen/MQTT-SberGate#5]
Что-то у меня не запустилась, вот что в логах:

20231009-213628: Неиспользуемый тип: binary_sensor.datchik_protechki_vanna_tamper
20231009-213628: Неиспользуемый тип: media_player.televizor_v_spalne_2
20231009-213628: Неиспользуемый тип: update.mqtt_sbergate_update
20231009-213629: SberDevice http_api_endpoint: https://mqtt-partners.iot.sberdevices.ru
Server started http://:9123
Start WebSocket Client
20231009-213629: Connect OK SberDevices Broker, rc: 0
20231009-213629: SD Subscribed: 2 (0,)
20231009-213629: SD Subscribed: 3 (0,)
WebSocket: opened
20231009-213629: WebSocket: auth_required
20231009-213629: WebSocket: auth_invalid
  File "/app/sber-gate.py", line 692, in <module>
    ws.run_forever()
  File "/usr/lib/python3.11/site-packages/websocket/_app.py", line 367, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened
WebSocket: Connection closed
Socket disconect
Connecting
WebSocket: opened
20231009-213630: WebSocket: auth_required
20231009-213630: WebSocket: auth_invalid
Socket disconect
Connecting
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by AlekseyPetrov75** [comment]
Я так понимаю надо 685 строку подправить в коде...

**Comment by JanchEwgen** [comment]
Да. Я сломал не дожидаясь долгих, зимних вечеров. Поторопился... ;)
Вроде бы уже исправил. Надеюсь заработало.
