### ISSUE TITLE
исправить ошибку   File "/app/sber-gate.py", line 414

### ISSUE THREAD

**Issue by JoolsJealous** [JanchEwgen/MQTT-SberGate#6]
Ошибка File "/app/sber-gate.py", line 414
    for s in res:
    ^
IndentationError: expected an indented block after function definition on line 412
************
**Поправил так:**
def upd_sw(id, s):
    attr = s['attributes'].get('friendly_name', '')
    log('switch: ' + s['entity_id'] + ' ' + attr)
    DevicesDB.update(s['entity_id'], {'entity_ha': True, 'entity_type': 'sw', 'friendly_name': attr, 'category': 'relay'})

def upd_scr(id, s):
    attr = s['attributes'].get('friendly_name', '')
    log('script: ' + s['entity_id'] + ' ' + attr)
    DevicesDB.update(s['entity_id'], {'entity_ha': True, 'entity_type': 'scr', 'friendly_name': attr, 'category': 'relay'})

def upd_default(id, s):
    pass  

for s in res:
    a, b = s['entity_id'].split('.', 1)
    dict = {
        'switch': upd_sw,
        'script': upd_scr
    }
    dict.get(a, upd_default)(s['entity_id'], s)

Вроде все заработало!

**Comment by JanchEwgen** [comment]
Спасибо.
Вроде проверял и такой ляп... :(

**Comment by JoolsJealous** [comment]
Вам спасибо за отличную интеграцию. )
