### ISSUE TITLE
Make it aviable as ADDON to homeassistant

### ISSUE THREAD

**Issue by lotohov** [JanchEwgen/MQTT-SberGate#7]
А вобще автор молодец ! но ещебы сделать из докера аддон к ha

**Comment by JanchEwgen** [comment]
Спасибо. Только я всегда считал, что все аддоны на докере сделаны. И весь агент изначально и делался как аддон. Аддон и есть. Разве не так?

**Comment by lotohov** [comment]
Ну чисто технический , так и есть , но в homeassistant своя подсистема основанная на докере , позволяющая устанавливать дополнения по клику ну и со своими ограничениями. почитать можно https://developers.home-assistant.io/docs/add-ons/tutorial

**Comment by JanchEwgen** [comment]
> устанавливать дополнения по клику

Не совсем понял что значит устанавливать по клику. Прочитал по диагонали, ничего вроде нового не увидел. В последних версиях я изменил структуру каталогов и теперь можно ставить добавив в магазин ссылку на GitHub (https://github.com/JanchEwgen/MQTT-SberGate). Есть вариант ещё проще?

**Comment by lotohov** [comment]
Нет , проще нет , я не увидел этой возможности сразу , думал только через докер. Завтра буду пробовать , спасибо за ответ.

**Comment by lotohov** [comment]
Проблема решена
