### ISSUE TITLE
добавть домен light

### ISSUE THREAD

**Issue by tayanov** [JanchEwgen/MQTT-SberGate#8]
Добавить объекты домена light. Как базовые обьекты управления светом. Сейчас В списке только сенсоры, скрипты и свитчи. Других сущностей нет.

**Comment by JanchEwgen** [comment]
Можно считать добавленным. Но как-то всё стало загадочно работать... ;)
Кстати картинки теперь в приложении Сбера при желании можно изменить поменяв категорию в UI от Сбера. Надеюсь ничего падать не будет.
