### ISSUE TITLE
Дополнение запускается, но через некоторое время останавливается.

### ISSUE THREAD

**Issue by slowlyup** [JanchEwgen/MQTT-SberGate#9]
Home Assistant 2023.10.5
Supervisor 2023.11.3
Operating System 11.1

Долгосрочный токен доступа создан и сохранён в поле ha-api_token.
Дополнение запускается, но веб интерфейс не открывается. Через несколько минут дополнение останавливается.
Лог:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
20231122-192626.587352: Start MQTT SberGate IoT Agent for Home Assistant version: 1.0.9
20231122-192626.587435: Запущено в системе: posix
20231122-192626.587478: Версия Python     : 3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924]
20231122-192626.587688: Размещение скрипта: /app/sber-gate.py
20231122-192626.587747: Текущая директория: /data
20231122-192626.587893: Список файлов     : ['options.json', 'devices.json']
20231122-192626.587935: Кодировка: utf-8
20231122-192626.588246: Чтение базы
20231122-192626.597236: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192631.601472: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192636.605697: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192641.610491: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192646.614249: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192651.618248: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192656.623867: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192701.627957: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192706.632241: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
20231122-192711.636900: Ошибка подключения к HA. Ждём 5 сек перед повторным подключением.
Traceback (most recent call last):
  File "/app/sber-gate.py", line 458, in <module>
    if res.status_code == 200:
       ^^^
NameError: name 'res' is not defined
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by JanchEwgen** [comment]
Ошибка подключения к HA однако. Поэтому и останавливается. Если с токеном всё правильно, нужно посмореть ha-api_url, в конце строки не должно быть /

**Comment by slowlyup** [comment]
Токены делал от разных пользователей (основной и сделанный для дополнения), слэша в ha-api_url нет.

![изображение](https://github.com/JanchEwgen/MQTT-SberGate/assets/109545832/0dc87d7c-c018-4e02-bcd5-fa7a72d14c24)

**Comment by slowlyup** [comment]
Поменял в ha-api_url localhost на ip адрес и запустилось.

**Comment by JanchEwgen** [comment]
Вот и хорошо. Надо будет добавить в описание, что localhost не катит.
